### PR TITLE
fix(mapping): removes DockerClientDefaults from ctlgRef

### LINKED ISSUE #423: Using catalog image with digest causes error
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-1-g1f3f725", GitCommit:"1f3f725", GitTreeState:"clean", BuildDate:"2022-04-18T14:02:05Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}

```

# What happened?

I see an error when using an image and digest in an ImageSetConfiguration instead of an image and tag.

# What did you expect to happen?

I expected to be able to use either `image:tag` or `image@digest` in my ImageSetConfiguration.

# How to reproduce it (as minimally and precisely as possible)?

1. Create a valid ImageSetConfiguration using `image:tag`

```yaml
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:5000/test:latest # Stores metadata in an image
    skipTLS: true # Disable TLS certificate checking or use plain HTTP
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8 # References entire catalog
      full: true # AllPackages can be set to pull a full catalog and must be set to filter packages
      packages:
        - name: rhacs-operator
          startingVersion: '3.67.0'
          channels:
            - name: 'latest'
```

2. Verify that the oc-mirror request is successful:

```console
$ oc-mirror --config test-catalog.yaml file://archive/
```

3. Clean up that request and get the digest for the catalog (I'm using skopeo)

```console
$ skopeo inspect docker://registry.redhat.io/redhat/redhat-operator-index:v4.8 | jq .Digest
"sha256:b9cd0cbfb0a2552866565864779e06f5a8f09838a2c8d7597be47c600d9e601f"
```

4. Update the ImageSetConfiguration to use `image@digest`:

```yaml
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:5000/test:latest # Stores metadata in an image
    skipTLS: true # Disable TLS certificate checking or use plain HTTP
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index@sha256:b9cd0cbfb0a2552866565864779e06f5a8f09838a2c8d7597be47c600d9e601f # References entire catalog
      full: true # AllPackages can be set to pull a full catalog and must be set to filter packages
      packages:
        - name: rhacs-operator
          startingVersion: '3.67.0'
          channels:
            - name: 'latest'
```

5. Attempt to run the mirror command:

```console
oc-mirror --config test-catalog.yaml file://archive
INFO Found: archive/oc-mirror-workspace/src/publish 
INFO Found: archive/oc-mirror-workspace/src/v2    
INFO Found: archive/oc-mirror-workspace/src/charts 
INFO No metadata detected, creating new workspace 
WARN[0016] DEPRECATION NOTICE:
Sqlite-based catalogs and their related subcommands are deprecated. Support for
them will be removed in a future release. Please migrate your catalog workflows
to the new file-based catalog format. 
wrote mirroring manifests to archive/oc-mirror-workspace/operators.1650377358/manifests-redhat-operator-index

To upload local images to a registry, run:

	oc adm catalog mirror file://redhat/redhat-operator-index@sha256:b9cd0cbfb0a2552866565864779e06f5a8f09838a2c8d7597be47c600d9e601f REGISTRY/REPOSITORY
error: repository name must have at least one component
```

# Anything else we need to know?

I've been asked to also create a Bugzilla entry for this and will need some assistance with it.

# References

Enter text here.

### PR DESCRIPTION
**Pull request by jpower432**
When reading the catalog reference provided by the configuration,
the run method in operator.go was modifying the reference in a way
that resulted in the reference differing from the mapping. The DockerClientDefaults
call has been removed and a SetDefaults method has been added to TypedImage as a way to set
fields in a standard way on this type.

Closes #423 

Signed-off-by: Jennifer Power <barnabei.jennifer@gmail.com>

# Description

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [X] Manually tested
- [X] Unit test for new method
- [X] Add e2e test case for an operator specified by digest

# How to Test

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: metadata
mirror:
    operators:
      - catalog: quay.io/redhatgov/oc-mirror-dev@sha256:f74bd3f08c971fafd64c9c95fe9839f54bf776d00ac363f2c3882c0e37c946ef
```
`oc-mirror --config imageset-config.yaml docker://localhost:5000/test`

This should not result in `error: repository name must have at least one component`

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: pkg/image/mapping.go [hunk 1]
```diff
@@ -25,7 +26,20 @@ func ParseTypedImage(image string, typ v1alpha2.ImageType) (TypedImage, error) {
...
 	}
-	return TypedImage{ref, typ}, nil
+	t := TypedImage{ref, typ}
+	return t.SetDefaults(), nil
+}
+
+// SetDefaults sets the default values for TypedImage fields
+func (t TypedImage) SetDefaults() TypedImage {
+	if len(t.Ref.Tag) == 0 {
+		if len(t.Ref.ID) > 13 {
```
Comment (dinhxuanvu) [inline pkg/image/mapping.go:36]: Magic numbers and random range below as well. A comment would be nice.

**Review by dinhxuanvu — COMMENTED** [review]
Looking good. Just a few comments.

File: pkg/image/mapping.go (hunk 1 above)
Comment (jpower432) [reply pkg/image/mapping.go:36]: Thanks! I will add a comment. The number selection was arbitrary, get getting a tag from the first 6 characters from the digest. Only check that it's great than 13 to avoid an out-of-range panic.

Comment (jpower432) [reply pkg/image/mapping.go]: Decided to remove this altogether and just made a helper function to validate and get the partial digest so the solution does not diverge in these two places.

File: pkg/image/digest.go [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+import "github.com/opencontainers/go-digest"
+
+// getPartialDigest returns the first 6 characters of a digest
+// if valid.
+func getPartialDigest(d string) (string, error) {
+	_, err := digest.Parse(d)
+	if err != nil {
+		return "", err
+	}
+	return d[7:13], nil
```
Comment (dinhxuanvu) [inline pkg/image/digest.go:12]: Given the input is just a string, probably should add a bit more context here to clarify things. This is an image digest with the format `sha256:xxxxxx`. So from 0:6 is `sha256:`, digest prefix and the rest of the SHA digest which you attend to get the first 6 characters. Plus should we check the length first here to ensure it has more than 13 characters to avoid out of bound error even though normally the SHA256 digest should be sufficiently longer than 6 characters?

Comment (jpower432) [reply pkg/image/digest.go:24]: Added more context with an example of the intended result. Also added the length check, while I agree the digest validation should catch this, better safe than to panic.

**Review by dinhxuanvu — APPROVED** [review]
/lgtm
