### PR TITLE
fix(operator): produce error when invalid packages are provided with …

### LINKED ISSUE #246: oc-mirror compression issue.
Screen Shot 2021-12-17 at 12 25 31 PM
Screen Shot 2021-12-15 at 2 50 52 PM

# Version

```console
$ oc-mirror version
<your output here>
```

# What happened?

oc-mirror stopped after pulling the blob and manifest, and did not compress the mirror. 
Attach the relevant portions of your `.openshift_bundle.log`.

# What you expected to happen?

I expected to have a tar file at the end of the pull. 

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Please see attached. 

# References

### PR DESCRIPTION
**Pull request by jpower432**
…catalog

Fixes #246

Signed-off-by: Jennifer Power <barnabei.jennifer@gmail.com>

# Description

This PR fixes an uncaught error in `operators.go` when `action.Diff` is run. This error in relation to the ticket it is closing was not reporting an error when invalid packages were passed in the config.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Unit tests will be added to validate this fix

- [ ] operator unit test

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: pkg/cli/mirror/operator.go [hunk 1]
```diff
@@ -191,6 +191,9 @@ func (o *OperatorOptions) renderDCFull(ctx context.Context, reg *containerdregis
 			IncludeAdditively: includeAdditively,
 			SkipDependencies:  ctlg.SkipDependencies,
 		}.Run(ctx)
+		if err != nil {
+			return nil, err
+		}
 	}
 
 	return dc, err
```
Comment (estroz) [inline pkg/cli/mirror/operator.go:199]: That error gets returned here.

File: docs/imageset-config-ref.yaml [hunk 2]
```diff
@@ -17,11 +17,10 @@ mirror:
     - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8 # References entire catalog
       headsOnly: true # References latest version of each operator in catalog (true is the default value and can be omitted)
       packages:
-        - name: couchbase-operator # Planned, overrides catalog default, respects headsOnly setting
```
Comment (estroz) [inline docs/imageset-config-ref.yaml:20]: Does this need to be changed back?

File: pkg/cli/mirror/operator.go [hunk 3]
```diff
@@ -191,6 +191,9 @@ func (o *OperatorOptions) renderDCFull(ctx context.Context, reg *containerdregis
 			IncludeAdditively: includeAdditively,
 			SkipDependencies:  ctlg.SkipDependencies,
 		}.Run(ctx)
+		if err != nil {
+			return nil, err
+		}
 	}
```
Comment (estroz) [inline pkg/cli/mirror/operator.go:197]: So the error is always caught for both branches
```suggestion
	}
	if err != nil {
		return nil, err
	}
```

File: pkg/cli/mirror/operator.go (hunk 1 above)
Comment (estroz) [reply pkg/cli/mirror/operator.go:199]:
```suggestion
	return dc, nil
```

File: pkg/cli/mirror/operator.go [hunk 4]
```diff
@@ -578,3 +586,10 @@ func parseRelatedImages(root string) (map[string]struct{}, error) {
 	delete(relatedImages, "")
 	return relatedImages, nil
 }
+
+func validate(dc *declcfg.DeclarativeConfig) error {
+	if dc == nil {
+		return errors.New("nil declarative config")
```
Comment (estroz) [inline pkg/cli/mirror/operator.go:592]: Since dc should never be nil, I'd treat this as a bug so people know to file an issue
```suggestion
		return errors.New("bug: nil declarative config")
```

File: pkg/cli/mirror/operator.go (hunk 3 above)
Comment (estroz) [reply pkg/cli/mirror/operator.go:197]: Oh I see what the issue is. Disregard this.

File: docs/imageset-config-ref.yaml (hunk 2 above)
Comment (jpower432) [reply docs/imageset-config-ref.yaml:20]: I updated this just to give an example of a real package that existed in the catalog because I noticed providing invalid packages in the config ref was causing some confusion for users.

**Review by estroz — COMMENTED** [review]
/lgtm
