### PR TITLE
Bug 2087271: fix(mirror): adds sequence checks for mirror to mirror operations

### LINKED ISSUE #468: [bug] m2m completes successfully when publishing to incorrect namespace
# Version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-36-g7d88d4e", GitCommit:"7d88d4e8", GitTreeState:"clean", BuildDate:"2022-05-16T20:28:02Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}

# What happened?

when publishing m2m differential synchronizations, if an incorrect namespace is targeted for publishing, oc-mirror does not produce a sequence error as expected. 

# What did you expect to happen?

differential syncs should error if published to a different registry namespace than previous syncs. 

# How to reproduce it (as minimally and precisely as possible)?

publish a to a mirror registry namespace and then use m2m to publish a diff to a different namespace.

### PR DESCRIPTION
**Pull request by jpower432**
# Description
Currently, mirror to mirror operations do not check the sequence number
when publishing since there are no layer differential considerations.
However, sequence checking still needs to be done to ensure the
target namespace is not changed on a differentials run.

Fixes #468

Signed-off-by: Jennifer Power <barnabei.jennifer@gmail.com>

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [X] Unit tests added for new helper function
- [X] Testing changing the namespace on a managed workspace with mirror to mirror

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jpower432** [comment]
@afflom This PR is ready for testing.

File: pkg/cli/mirror/mirror.go [hunk 1]
```diff
@@ -682,6 +676,28 @@ func (o *MirrorOptions) generateResults(mapping image.TypedImageMapping, dir str
 	return WriteICSPs(dir, allICSPs)
 }
 
+func (o *MirrorOptions) copyToResults(resultsDir string) error {
```
Comment (dinhxuanvu) [inline pkg/cli/mirror/mirror.go:679]: Unusual functionality. It is more like a renaming than actual moving.

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm
