### PR TITLE
Stopping the process when no changes are found between runs. [190]

### LINKED ISSUE #190: Do not generate imageset on no updates
# Version
Alpha3

# What happened?

No updates were mirrored during imageset creation, but an empty imageset was generated.

# What you expected to happen?

If there was nothing mirrored during creation, I would not expect an imageset to be generated.

# How to reproduce it (as minimally and precisely as possible)?

run oc-mirror with a single operator selected that would normally return 404 (missing) and add --skip-missing as a command line flag.

# Anything else we need to know?

This is problematic because it updates the imageset sequence number and forces the user to publish an empty imageset.

### PR DESCRIPTION
**Pull request by ianwatsonrh**
# Description

Checks if there are any blob differences during the process. If there are no changes stop the process to avoid unnecessary sequence update / tar files with only the manifests in. 

Fixes #190

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit tests updated
- [x] Run yourself via two runs of oc-mirror --config imageset-config.yaml file://archives and oc-mirror --config imageset-config.yaml file://archives2. Note that in archives2 there are no tar files. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: pkg/cli/mirror/create_test.go [hunk 1]
```diff
@@ -132,3 +179,19 @@ func TestCreateWithCancel(t *testing.T) {
 
 	require.Equal(t, true, opts.interrupted)
 }
+
+func GenerateConfigPath(path string, baseFile string, targetFile string) {
```
Comment (jpower432) [inline pkg/cli/mirror/create_test.go:183]: Nit: This function could be private if it will just be used in this test file

Comment (ianwatsonrh) [reply pkg/cli/mirror/create_test.go]: Ack. Changed to private.

File: pkg/cli/mirror/create.go [hunk 2]
```diff
@@ -126,6 +126,12 @@ func (o *MirrorOptions) Create(ctx context.Context) error {
 	if err != nil {
 		return err
 	}
+
+	// Stop the process if no new blobs
+	if len(blobs) == 0 {
```
Comment (jpower432) [inline pkg/cli/mirror/create.go:131]: @ianwatsonrh One thing I would suggest here is having a logging message to signal to the user that an image will not be created. Something like "no updates detected". Other than that it LGTM.

Comment (ianwatsonrh) [reply pkg/cli/mirror/create.go:131]: Ack. Log line added.

**Comment by afflom** [comment]
Very cool! It works as advertised. I only noticed one issue when I tested it mirror2mirror. The log output might be a bit confusing to users. Can you please configure it to exit without calling the publishing functions when using mirror2mirror?: 
```
INFO no updates detected, process stopping        
INFO Publishing image set from archive "./mirrortmp468199673" to registry "registry.test.com:5000" 
DEBUG Unarchiving metadata into oc-mirror-workspace/images.178718783 
Image Publish:
ERROR: publishing operation failed: no archives found in directory ./mirrortmp468199673
To retry this operation run "oc-mirror --from ./mirrortmp468199673 docker://registry.test.com:5000
```

**Comment by jpower432** [comment]
> 

@afflom good catch on the mirror2mirror error @ianwatsonrh Maybe instead of returning nil, you could return a custom error that can be handled by the caller since we use the `Create` function in multiple places.

**Comment by ianwatsonrh** [comment]
> @afflom good catch on the mirror2mirror error @ianwatsonrh Maybe instead of returning nil, you could return a custom error that can be handled by the caller since we use the `Create` function in multiple places.

Ack. 

Custom error thrown instead of nil. Caller then handles the error. 

New e2e-simple test case added to reflect.

**Comment by afflom** [comment]
Spot on. Give me the weekend to play with it and I'll get back to you.

**Comment by jpower432** [comment]
Tested and everything works as expected
/lgtm
