### PR TITLE
fix: adds validation for ImageSetConfiguration and add insecure to na…

### LINKED ISSUE #248: Config validation do not allow headsOnly=true with package selection
# What happened?

headsOnly=true overrides package selection and downloads the entire catalog channel heads. 

# What you expected to happen?

headsOnly=true with package selection is currently disallowed by operator-registry. So this configuration should return an error. 

Long term, headsOnly with package or channel selection should mirror the package/channel head versions, but this will not happen until at least GA. 

# Solution

For now, headsonly=true with package selection should be an illegal configuration and return an error during config validation.

### PR DESCRIPTION
**Pull request by jpower432**
…me options for CheckPushPermissions

Closes #248

Signed-off-by: Jennifer Power <barnabei.jennifer@gmail.com>

# Description

This PR add initial validations for the ImageSetConfiguration and fixes an issue when using insecure registry with FQDN.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Unit tests added/edited

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: pkg/cli/mirror/catalog_images.go [hunk 1]
```diff
@@ -229,12 +228,11 @@ func (o *MirrorOptions) buildCatalogLayer(ctx context.Context, srcRef, targetRef
...
 	logrus.Debugf("Pulling image %s for processing", srcRef)
 	// Pull source reference image
-	ref, err := name.ParseReference(srcRef)
+	ref, err := name.ParseReference(srcRef, o.getNameOpts()...)
 	if err != nil {
 		return err
 	}
-	options := o.getRemoteOpts(ctx)
-	img, err := remote.Image(ref, options...)
+	img, err := remote.Image(ref, o.getRemoteOpts(ctx)...)
```
Comment (estroz) [inline pkg/cli/mirror/catalog_images.go:235]: Is there a reason to re-create these options on each call?

Comment (jpower432) [reply pkg/cli/mirror/catalog_images.go:235]: When I was initially writing this section, I stored the options in the MirrorOptions struct, but it broke the unit test since the `remote.Option` and `name.Option` types are functions that take pointer arguments. I created a helper function as an alternative, but I am totally open to suggestions on better ways to do this.

**Comment by afflom** [comment]
Tested. Works

File: pkg/cli/mirror/mirror.go [hunk 2]
```diff
@@ -203,8 +206,39 @@ func (o *MirrorOptions) Run(cmd *cobra.Command, f kcmdutil.Factory) (err error)
...
-	transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: o.DestSkipTLS}
-	return transport
+func (o *MirrorOptions) getRemoteOpts(ctx context.Context) (options []remote.Option) {
+	return append(
+		options,
+		remote.WithAuthFromKeychain(authn.DefaultKeychain),
+		remote.WithTransport(o.createRT()),
+		remote.WithContext(ctx),
+	)
+}
```
Comment (estroz) [inline pkg/cli/mirror/mirror.go:216]: Unnecessary append
```suggestion
func (o *MirrorOptions) getRemoteOpts(ctx context.Context) []remote.Option {
	return []remote.Option{
		remote.WithAuthFromKeychain(authn.DefaultKeychain),
		remote.WithTransport(o.createRT()),
		remote.WithContext(ctx),
	}
}
```

File: pkg/config/validate.go [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+	"github.com/openshift/oc-mirror/pkg/config/v1alpha1"
+	utilerrors "k8s.io/apimachinery/pkg/util/errors"
+)
+
+type validationFunc func(cfg v1alpha1.ImageSetConfiguration) error
+
+var validationChecks = []validationFunc{validateOperatorOptions}
+
+func Evaluate(cfg v1alpha1.ImageSetConfiguration) error {
```
Comment (estroz) [inline pkg/config/validate.go:14]: Usually this is just called Validate

**Review by estroz — COMMENTED** [review]
Looks great!

/lgtm
