### PR TITLE
Bug 2075050: fix: adds handling for channel with different prefixes in cincinnati.go

### LINKED ISSUE #292: Terminated mirror run from: NoVersionsFound issue caused by look-ahead to an empty fast-4.10 channel
# Version

```console
$ oc-mirror version
v0.1.0-alpha.3
```

# What happened?
I have published two different "fast-4.8" channel upgrades to this cluster through my first three sequences 4.8.26 and 4.8.27.
In this next step, my fourth sequence, I attempted to mirror a version from the "fast-4.8" channel: 4.8.28
```
$ oc-mirror list releases --version=4.8 --channel=fast-4.8
Channel: fast-4.8
4.7.0
4.7.1
.
.
.
4.8.27
4.8.28
```
So created this imageset:
```
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: quay.jimbarlow.com/jimbarlow/metadata:oc-mirror
    skipTLS: false
mirror:
  ocp:
    channels:
      - name: fast-4.8
        versions:
          - '4.8.28'
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8
      headsOnly: false
      packages:
        - name: quay-operator
          startingVersion: '3.5.7'
          channels:
            - name: quay-v35
```
The here is my command output:
```
$ oc-mirror --config imageset-4.8.28.yaml file://output-dir --log-level=debug
DEBUG Using registry backend at location quay.jimbarlow.com/jimbarlow/metadata:oc-mirror 
DEBUG Checking for existing metadata image at quay.jimbarlow.com/jimbarlow/metadata:oc-mirror 
DEBUG looking for metadata file at "publish/.metadata.json" 
INFO Found: output-dir/oc-mirror-workspace/src/publish 
INFO Creating directory: output-dir/oc-mirror-workspace/src/v2 
INFO Creating directory: output-dir/oc-mirror-workspace/src/charts 
INFO Downloading requested release 4.8.28         
DEBUG Found current release 4.8.27                 
DEBUG Processing channel fast-4.9                  
DEBUG Getting updates for latest 4.8.27 in channel fast-4.9 
DEBUG Processing channel fast-4.10                 
error: failed to get upgrade graph: NoVersionsFound: no cluster versions found in the "fast-4.10" channel
```
It doesn't matter if I use graph: true or graph:false (not sure it is implemented yet)

# What you expected to happen?
I expected that I would be able to mirror 4.8.28, without it failing because of a future 4.10 concern.

This issue can be consistently reproduced with my steps above.

# Anything else we need to know?
I would have expected a NoVersionsFound issue to be a warning rather than an error

### PR DESCRIPTION
**Pull request by jpower432**
Currently, the prefix for the target channels is being inferred from the source channel
when calculating Cincinnati graphs. This can cause an issue when the prefix of the channel
is different for the starting and target version. Now, the starting prefix is only
used when calculating upgrades through the channel until the target major and minor version
is reached.

Fixes #292 

Signed-off-by: Jennifer Power <barnabei.jennifer@gmail.com>

# Description

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [X] Case added to unit test for channels with different prefixes

# Testing scenarios
```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: metadatafake
mirror:
  platform:
    channels:
    - name: stable-4.10
    - name: fast-4.10 
```
`oc-mirror --config imageset-config.yaml file://archives`

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: pkg/cincinnati/cincinnati.go [hunk 1]
```diff
@@ -177,16 +177,36 @@ func CalculateUpgrades(ctx context.Context, c Client, arch, sourceChannel, targe
 		return GetUpdates(ctx, c, arch, targetChannel, startVer, reqVer)
 	}
 
+	// Check the major and minor versions are the same with different
+	// channel prefixes
+	source, target, _, err := getSemverFromChannels(sourceChannel, targetChannel)
+	if err != nil {
+		return Update{}, Update{}, nil, err
```
Comment (dinhxuanvu) [inline pkg/cincinnati/cincinnati.go:184]: Should it be `return source, target, nil, err` instead?

**Review by dinhxuanvu — COMMENTED** [review]
Just one quick question.

File: pkg/cincinnati/cincinnati.go (hunk 1 above)
Comment (jpower432) [reply pkg/cincinnati/cincinnati.go:184]: `source` and `target` are the `semver.Version` representation of the source and target channel suffixes (e.g. source could be 4.9.0 and target could be 4.10.0). So in this case no, but maybe a variable rename or comment could make that more clear.

**Review by dinhxuanvu — APPROVED** [review]
/lgtm
